name: 'R2 upload'
description: 'Upload a file to cloudflare R2 storage'
inputs:
  account-id:
    description: 'R2 Account ID'
    required: true
  access-key-id:
    description: 'R2 Access key id'
    required: true
  secret-access-key:
    description: 'R2 Secret access key'
    required: true
  r2-bucket:
    description: 'R2 destination bucket'
    required: true
  r2-path:
    description: 'Destination path'
    required: false
  file-info:
    description: 'Array with objects containing path and contentType of every file to upload'
    required: true

outputs:
  data:
    description: 'Response from R2'
runs:
  using: 'node16'
  main: 'dist/index.js'